# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: c

matrix:
  include:
    # do one build run with our minimum dependencies
    # (or, well, at least the lowest version number that is available through
    #  anaconda..)
    - os: linux
      env: PYTHON_VERSION=3.7

    - os: osx
      env: PYTHON_VERSION=3.7

sudo: false


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
    else
      export OS="Linux";
    fi

  # Python and related stuff
  - if [[ "${PYTHON_VERSION:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
#  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q --yes conda
  # Installs required packages
  - conda install --yes -q -c conda-forge pip python=$PYTHON_VERSION
  - conda install --yes -q -c conda-forge numpy scipy matplotlib statsmodels pandas sqlalchemy
  - conda install --yes -q -c conda-forge sphinx jinja2 flask pymysql click
  - conda install --yes -q -c conda-forge lxml pyqt
  - conda install --yes -q -c conda-forge pyproj shapely
  - conda install --yes -q -c conda-forge obspy
  - conda install --yes -q -c conda-forge flask-admin markdown codecov logbook
  - pip install multiprocessing_logging
  - pip install msnoise
  - ls -la

install:
  - python setup.py bdist_wheel
  - python setup.py install
  - cd

script:
  - mkdir empty
  - cd empty
  - msnoise db init --tech 1
  - msnoise config set plugins=msnoise_tomo
  - msnoise p tomo install
  - msnoise p tomo info

deploy:
  provider: bintray
  file: "bintray.json"
  user: "thomaslecocq"
  key: "$BINTRAY_API"
  skip_cleanup: true # to upload artifacts created during the build
